### ISSUE TITLE
训练数据集问题

### ISSUE THREAD

**Issue by ownthink** [MU94W/WaveGlow#2]
作者您好，看代码里只有音频的处理，并没发现哪边有音频的标注，如何做到输入文本输出音频呢。多谢！！！

**Comment by MU94W** [comment]
> 作者您好，看代码里只有音频的处理，并没发现哪边有音频的标注，如何做到输入文本输出音频呢。多谢！！！

你好，waveglow的论文模型输入是对数梅尔谱，输入linguistic feature应该是类似的。直接输入文本是不行的哈，你可以用另一个网络来预测声学参数。

**Comment by ownthink** [comment]
多谢解答！
